In [1]:
import pandas as pd

In [2]:
NED_DATASET_PATH = "./datasets/ned_dataset.csv"
SCARA_DATASET_PATH = "./datasets/scara_dataset.csv"

In [3]:
ned_data = pd.read_csv(NED_DATASET_PATH)
scara_data = pd.read_csv(SCARA_DATASET_PATH)

In [4]:
ned_data.head()

,is_scara,is_ned,q1,q2,q3,x,y,z
0,0,1,0.235954,0.258724,-0.233114,-0.074332,0.310027,0.416754
1,0,1,0.436384,0.312437,-0.488395,-0.134191,0.288299,0.462275
2,0,1,-0.524758,-0.403500,0.139043,0.077646,0.133617,0.484390
3,0,1,-0.229266,-0.477743,-0.745246,-0.009754,-0.043406,0.622017
4,0,1,-0.834425,-0.451355,-0.892419,-0.051202,-0.046913,0.628133

In [5]:
scara_data.head()

,is_scara,is_ned,q1,q2,q3,x,y,z
0,1,0,-0.258182,0.006656,-0.067448,0.606249,-0.142499,0.114524
1,1,0,-0.213587,-0.314008,-0.094272,0.581391,-0.193273,0.087700
2,1,0,-0.350602,0.064471,-0.013080,0.595600,-0.178405,0.168892
3,1,0,0.432594,0.139003,-0.049537,0.556096,0.267973,0.132435
4,1,0,0.243958,0.478314,-0.042797,0.553871,0.244227,0.139175

In [6]:
ned_data.describe()

,is_scara,is_ned,q1,q2,q3,x,y,z
count,25000.0,25000.0,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,0.0,1.0,0.001076,-0.153114,-0.302128,0.000238,0.022249,0.493973
std,0.0,0.0,1.554434,0.317285,0.636742,0.148611,0.125291,0.125575
min,0.0,1.0,-2.699892,-0.699973,-1.399882,-0.348283,-0.309437,0.154442
25%,0.0,1.0,-1.350786,-0.427058,-0.857260,-0.113846,-0.060668,0.397151
50%,0.0,1.0,-0.006935,-0.156342,-0.301260,0.000284,0.011561,0.527532
75%,0.0,1.0,1.348363,0.121352,0.251364,0.113723,0.108794,0.605130
max,0.0,1.0,2.699318,0.399895,0.799966,0.347966,0.347573,0.645868

In [7]:
scara_data.describe()

,is_scara,is_ned,q1,q2,q3,x,y,z
count,25000.0,25000.0,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,1.0,0.0,-0.002794,0.000340,-0.074916,0.550509,-0.000760,0.107056
std,0.0,0.0,0.420648,0.479547,0.043243,0.065073,0.237294,0.043243
min,1.0,0.0,-0.729997,-0.829918,-0.150008,0.293488,-0.457407,0.031965
25%,1.0,0.0,-0.365654,-0.417695,-0.112465,0.522014,-0.194331,0.069507
50%,1.0,0.0,-0.001871,0.005094,-0.074285,0.571018,-0.001266,0.107688
75%,1.0,0.0,0.360951,0.414289,-0.037606,0.598452,0.192361,0.144366
max,1.0,0.0,0.729977,0.829961,-0.000013,0.624585,0.464343,0.181959

## Combine both NED and SCARA datasets

In [8]:
combined_data = pd.concat([ned_data, scara_data], ignore_index=True)

In [9]:
combined_data.describe()

,is_scara,is_ned,q1,q2,q3,x,y,z
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,0.500000,0.500000,-0.000859,-0.076387,-0.188522,0.275374,0.010745,0.300515
std,0.500005,0.500005,1.138676,0.413765,0.465358,0.298095,0.190091,0.215050
min,0.000000,0.000000,-2.699892,-0.829918,-1.399882,-0.348283,-0.457407,0.031965
25%,0.000000,0.000000,-0.576350,-0.422847,-0.301252,0.000287,-0.113837,0.107688
50%,0.500000,0.500000,-0.002961,-0.091500,-0.089413,0.324142,0.008273,0.181226
75%,1.000000,1.000000,0.574599,0.240329,-0.019315,0.571018,0.142894,0.527532
max,1.000000,1.000000,2.699318,0.829961,0.799966,0.624585,0.464343,0.645868

In [10]:
combined_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   is_scara  50000 non-null  int64
 1   is_ned    50000 non-null  int64
 2   q1        50000 non-null  float64
 3   q2        50000 non-null  float64
 4   q3        50000 non-null  float64
 5   x         50000 non-null  float64
 6   y         50000 non-null  float64
 7   z         50000 non-null  float64
dtypes: float64(6), int64(2)
memory usage: 3.1 MB

## Shuffle combined dataset

In [11]:
shuffled_data = combined_data.sample(frac=1, random_state=42, ignore_index=True)

In [12]:
shuffled_data.head()

,is_scara,is_ned,q1,q2,q3,x,y,z
0,1,0,0.341700,-0.788656,-0.052945,0.577740,-0.005921,0.129027
1,0,1,1.078752,0.192634,0.761283,-0.204516,0.109663,0.206201
2,0,1,-2.652503,0.264075,-0.374363,0.146819,-0.276348,0.450027
3,0,1,1.190232,-0.436801,-0.931734,0.067656,-0.026666,0.629680
4,1,0,0.147300,0.481437,-0.117415,0.574681,0.196077,0.064557

## Export shuffled dataset into CSV format

In [13]:
DATASET_FILE_NAME = "./datasets/combined_dataset.csv"

In [14]:
shuffled_data.to_csv(DATASET_FILE_NAME, index=False)